spring:
  profiles:
    active: utest

##
logging:
  level:
    org.springframework: WARN
    com.alibaba: WARN
    com.corpnet: DEBUG

server:
  port: 9088
  session:
      timeout: 120

# 远程服务调用的设置
service:
  invoke:
    footprint:
      timeout: 60   #任务执行标记的超时时间,单位秒
    lock:
      timeout: 60   #任务锁的超时时间,单位秒
  delayqueue:
    wait: 500       #延迟队列的等待时间,单位毫秒
    sleep: 500      #延迟队列轮询为空时的睡眠时间,单位毫秒